#!/usr/bin/env python3

""" - Main program code for "floopcount" - A program to count the number of 
Fermion loops of Feynman graphs. 

This program is part of the feyncop/feyngen package.
"""

# See also: http://people.physik.hu-berlin.de/~borinsky/

__author__ = "Michael Borinsky"
__email__ = "borinsky@physik.hu-berlin.de"
__copyright__ = "Copyright (C) 2014 Michael Borinsky"
__license__ = "MIT License"
__version__ = "1.0"

# Copyright (c) 2014 Michael Borinsky

# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to 
# deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
# IN THE SOFTWARE.

# If you have problems using this program, 
# please feel free to contact me!
# March 2014

from fractions import *
import copy
import argparse
import sys
import collections
from math import *
from stuff import *

import parsefg, outputfg

from graph import Graph
from hopf_graph import HopfGraph

def main():
    """Main program section. Reads the options and parameters and starts the 
        relevant subroutines."""

    parser = argparse.ArgumentParser(description='Count the number of Fermion loops for each graph')
    parser.add_argument('-f', '--filter', dest='fermion_loops', type=int, default=-1, help='Filter for diagrams with # fermion loops')
    args = parser.parse_args()
        
    filt = -1 != args.fermion_loops
    string = ""
    try:
        string = next(sys.stdin)
    except StopIteration:
        return

    var_name,ev,el = parsefg.parse_var_name(string)
    if var_name:
        if filt:
            sys.stdout.write("%s_flc%s" % (var_name, string[ev:]))
        string = string[el:]

    def fermion_loops( g ):
        f_l, f_l_edges = g.cycle_decomposition( g.sub_edges_by_weight(1) )

        return len( f_l_edges )

    graphs_fac = ( (fermion_loops(g),g,fac,ym) for g,fac,ym in parsefg.parse_input_lines( sys.stdin, None, string ))

    graph_counter = collections.Counter()
    for fl, g, fac, ym in sorted(graphs_fac):
        graph_counter[fl] += 1
        g_str = g.get_graph_str( ym )
        if g_str and filt and args.fermion_loops == fl:
            print(outputfg.get_element_str( g_str, fac ))

    if filt:
        print(";")
    else:
        for fl, number in graph_counter.iteritems():
            print("%d graphs with %d fermion loops" % (number, fl))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("")
        print("Cancelled")
